codecov:
    require_ci_to_pass: no
    max_report_age: off

comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]


coverage:
    precision: 2
    round: down
    status:
        project:
            default:
                target: 95
                informational: true
        patch: off
        changes: off

ignore:
    - "gcmt/test/*"
    - "doc/*"
    - "bin/*"
    - "gcmt/__init__.py"
    - "setup.py"