name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cubedsphere
  - pytest
  - codecov
  - pytest-cov
  - xarray
  - h5py
  - numpy
  - scipy
  - setuptools
  - netcdf4
  - pip
  - pip:
      - git+https://github.com/MITgcm/xmitgcm.git
      - miepython
      - petitRADTRANS==2.4.9
      - prt-phasecurve

