name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - xarray
  - cubedsphere
  - pytest
  - codecov
  - pytest-cov
  - matplotlib
  - astropy
  - numpy
  - scipy
  - setuptools
  - netcdf4
  - pandas>2.0.3
  - numba>=0.58.0
  - llvmlite>=0.41.0
