name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cubedsphere
  - pytest
  - codecov
  - pytest-cov
  - pip
  - pip:
      - git+https://github.com/MITgcm/xmitgcm.git
      - git+https://github.com/pydata/xarray.git
      - pylint==2.14.5
      - astroid==2.11.7

