name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cubedsphere
  - pytest
  - codecov
  - pytest-cov
  - pip
  - pip:
      - git+https://github.com/MITgcm/xmitgcm.git
      - git+https://github.com/pydata/xarray.git
