name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cubedsphere
  - pytest
  - codecov
  - pytest-cov
  - xarray
  - h5py
  - numpy=1.21.5
  - setuptools=61.2.0
  - netcdf4
  - pip
  - pip:
      - git+https://github.com/MITgcm/xmitgcm.git
      - miepython
      - petitRADTRANS==2.4.9
      - prt-phasecurve
