name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cubedsphere
  - pytest
  - codecov
  - xmitgcm
  - pytest-cov
  - matplotlib
  - astropy
  - numpy
  - scipy
  - setuptools
  - netcdf4
  - pandas
  - numba
  - corner
  - tqdm
  - h5py
  - pre-commit 
  - pymultinest
  - seaborn
  - pip