name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cubedsphere
  - pytest
  - codecov
  - pytest-cov
  - h5py
  - matplotlib
  - astropy
  - numpy
  - scipy
  - setuptools
  - netcdf4
  - pandas>2.0.3
  - numba>=0.58.0
  - llvmlite>=0.41.0
  - pip
  - pip:
      - git+https://github.com/MITgcm/xmitgcm.git
      - miepython
      - petitRADTRANS==2.4.9
      - prt-phasecurve

