name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cubedsphere
  - pytest
  - codecov
  - pytest-cov
  - xarray
  - numpy
  - fortran-compiler
  - toolchain3
  - pip
  - pip:
      - git+https://github.com/MITgcm/xmitgcm.git